global:
  scrape_interval:     15s

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: django-web
    static_configs:
      - targets: ['localhost:8000']
  - job_name: grafana
    static_configs:
      - targets: ['localhost:3000']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['localhost:9093']

